-- Create ENUM type for account type
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340_db_uomw_user;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account (
  account_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type account_type NOT NULL DEFAULT 'Client',
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Table structure for table `classification`
CREATE TABLE IF NOT EXISTS public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name VARCHAR NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  inv_make VARCHAR NOT NULL,
  inv_model VARCHAR NOT NULL,
  inv_year CHAR(4) NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR NOT NULL,
  inv_thumbnail VARCHAR NOT NULL,
  inv_price NUMERIC(9,0) NOT NULL,
  inv_miles INTEGER NOT NULL,
  inv_color VARCHAR NOT NULL,
  classification_id INTEGER NOT NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between classification and inventory
ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id)
ON UPDATE CASCADE;

-- Data for classification table
INSERT INTO public.classification (classification_name)
VALUES 
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- Data for inventory table
INSERT INTO public.inventory (
inv_make, inv_model, inv_year, inv_description, inv_image,
inv_thumbnail, inv_price, inv_miles, inv_color, classification_id
)

VALUES
('Chevy','Camaro','2018','If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!','/images/camaro.jpg','/images/camaro-tn.jpg',25000,101222,'Silver',2),

('Batmobile','Custom','2007','Ever want to be a super hero? now you can with the batmobile.','/images/batmobile.jpg','/images/batmobile-tn.jpg',65000,29887,'Black',1),

('FBI','Surveillance Van','2016','Do you like police shows? You will feel right at home driving this van.','/images/survan.jpg','/images/survan-tn.jpg',20000,19851,'Brown',1),

('Dog','Car','1997','Do you like dogs? This car is for you straight from the 90s.','/images/dog-car.jpg','/images/dog-car-tn.jpg',35000,71632,'White',1),

('Jeep','Wrangler','2019','Great for everyday driving and offroading.','/images/wrangler.jpg','/images/wrangler-tn.jpg',28045,41205,'Yellow',3),

('Lamborghini','Adventador','2016','This V-12 engine packs a punch in this sporty car.','/images/adventador.jpg','/images/adventador-tn.jpg',417650,71003,'Blue',2),

('Aerocar International','Aerocar','1963','This car converts into an airplane.','/images/aerocar.jpg','/images/aerocar-tn.jpg',700000,18956,'Red',1),

('Monster','Truck','1995','This beast comes with 60 inch tires.','/images/monster-truck.jpg','/images/monster-truck-tn.jpg',150000,3998,'Purple',1),

('Cadillac','Escalade','2019','Luxury SUV great for any occasion.','/images/escalade.jpg','/images/escalade-tn.jpg',75195,41958,'Black',4),

('GM','Hummer','2016','Do you have 6 kids and like to go offroading?','/images/hummer.jpg','/images/hummer-tn.jpg',58800,56564,'Yellow',4),

('Mechanic','Special','1964','With a little TLC it will run as good as new.','/images/mechanic.jpg','/images/mechanic-tn.jpg',100,200125,'Rust',5),

('Ford','Model T','1921','First car to be put into production.','/images/model-t.jpg','/images/model-t-tn.jpg',30000,26357,'Black',5),

('Mystery','Machine','1999','Scooby and the gang always solved mysteries with this van.','/images/mystery-van.jpg','/images/mystery-van-tn.jpg',10000,128564,'Green',1),

('Spartan','Fire Truck','2012','Comes with 1000 ft of hose and 1000 gallon tank.','/images/fire-truck.jpg','/images/fire-truck-tn.jpg',50000,38522,'Red',4),

('Ford','Crown Victoria','2013','Former police fleet vehicle available to the public.','/images/crwn-vic.jpg','/images/crwn-vic-tn.jpg',10000,108247,'White',5);

-- Modify Hummer description
UPDATE public.inventory
SET inv_description = REPLACE(inv_description,'small interiors','a huge interior')
WHERE inv_make='GM'
AND inv_model='Hummer';

-- Update image paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image,'/images','/images/vehicles'),
inv_thumbnail = REPLACE(inv_thumbnail,'/images','/images/vehicles');

-- Messaging table
CREATE TABLE IF NOT EXISTS public.message (
message_id INT GENERATED BY DEFAULT AS IDENTITY,
message_subject VARCHAR NOT NULL,
message_body TEXT NOT NULL,
message_created TIMESTAMP DEFAULT now() NOT NULL,
message_to INT NOT NULL,
message_from INT NOT NULL,
message_read BOOLEAN DEFAULT false NOT NULL,
message_archived BOOLEAN DEFAULT false NOT NULL,
CONSTRAINT message_pkey PRIMARY KEY (message_id),
CONSTRAINT to_fkey FOREIGN KEY (message_to) REFERENCES public.account(account_id) ON UPDATE CASCADE,
CONSTRAINT from_fkey FOREIGN KEY (message_from) REFERENCES public.account(account_id) ON UPDATE CASCADE
);

-- Service history table
CREATE TABLE IF NOT EXISTS service_records (
service_id SERIAL PRIMARY KEY,
inv_id INT NOT NULL,
service_date DATE NOT NULL,
mileage INT,
description TEXT NOT NULL,
cost NUMERIC(10,2) DEFAULT 0.00,
service_center VARCHAR(255),
next_service_date DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_vehicle FOREIGN KEY (inv_id) REFERENCES inventory(inv_id) ON DELETE CASCADE
);